# This is a config for E2B sandbox template.
# You can use template ID (cdqhu71zgg4okds1bljy) or template name (next-js-starter) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("next-js-starter") # Sync sandbox
# sandbox = await AsyncSandbox.create("next-js-starter") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('next-js-starter')

team_id = "a7e5f691-798b-4a34-b076-3813a39b1e96"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "next-js-starter"
template_id = "cdqhu71zgg4okds1bljy"
